version: "3.5"
services:
  locust:
    container_name: locust
    hostname: locust
    ports:
      - "8089:8089"
    image: "grubykarol/locust:1.2.3-python3.9-alpine3.12"
    environment:
      ATTACKED_HOST: http://nginx
      # LOCUST_MODE: master
      # LOCUST_MASTER_BIND_PORT: 5557
      TASK_DELAY_FROM: 5
      TASK_DELAY_TO: 30
      QUIET_MODE: "${QUIET_MODE:-false}"
    # command: locust -f --headless -u 1000 -r 100 --run-time 1h30m --stop-timeout 99
    volumes:
      - ./locust:/locust

  # slave:
  #   image: "grubykarol/locust:1.2.3-python3.9-alpine3.12"
  #   environment:
  #     ATTACKED_HOST: http://nginx
  #     LOCUST_MODE: worker
  #     LOCUST_MASTER_HOST: master
  #     LOCUST_MASTER_BIND_PORT: 5557
  #     NO_PROXY: master
  #     # TASK_DELAY_FROM: 5
  #     # TASK_DELAY_TO: 30
  #     QUIET_MODE: "${QUIET_MODE:-false}"
  #   volumes:
  #     - ./locust:/locust

  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass
    restart: always

  wordpress1:
    image: wordpress:5.4.2-php7.2-apache
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
      WORDPRESS_DB_NAME: db_name
    links:
      - db
    restart: always
    depends_on:
      - db
    # deploy:
    #   replicas: 3

  nginx:
    image: nginx:1.19.0
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./wordpress:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - "wordpress1"
    links:
      - "wordpress1"

volumes:
  db:
  wordpress:
