version: "3.5"
services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass
    restart: always

  wordpress1:
    image: wordpress:5.4.2-php7.2-apache
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
      WORDPRESS_DB_NAME: db_name
    links:
      - db
    restart: always
    depends_on:
      - db
    deploy:
      replicas: 5

  nginx:
    image: nginx:1.19.0
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./wordpress:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - "wordpress1"
    links:
      - "wordpress1"

volumes:
  db:
  wordpress:
